# Settings in the config.yml are overriding Squib's defaults. Anything in the main script will override this.

# DPI is used in making PDFs and in unit conversions
#dpi: 72

# Text hints are used to show the boundaries of text boxes.
# Can be enabled/disabled at the command-level, or set globally with `set`
#text_hint: '#F00'

# Show progress bars on the command line for potentially long-running operations
progress_bars: true

#Enable some custom colors that can be used in any color
custom_colors:
  wood_dark: '#552200'
  string_dark: '#800080'
  metal_dark: '#4d4d4d'
  glass_dark: '#008080'
  duct_tape_dark: '#333333'
  initiative: '#6a0816'
  take_one: '#161650'
  capacity: '#613e1b'
  remove: '#002255'
  title_color: '#383734'

#For reading image file command (e.g. png and svg), read from this directory instead
img_dir: img-color
#img_dir: img-bw
